{% set name = "compas_tna" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: d965b8ce485a9f1b0b976b0acf7391fac3af9b4617c612b5b4de5bb5c505da9c

build:
  noarch: python
  number: 2
  script: {{ PYTHON }} -m pip install . --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - compas

test:
  imports:
    - compas_tna
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: https://github.com/BlockResearchGroup/compas_tna
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: COMPAS package for Thrust Network Analaysis. This package provides the base implementation of TNA. For a RhinoVault-style user interface and workflow, see compas-RV2.
  doc_url: https://blockresearchgroup.github.io/compas_tna/
  dev_url: https://github.com/BlockResearchGroup/compas_tna

extra:
  recipe-maintainers:
    - tomvanmele
    - licini
