{% set name = "compas_tna" %}
{% set version = "0.5.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a1e0ade26f44eec90a73324ea449653e5073a9735be2a0949bf1e8fbecdde0eb

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - compas

test:
  imports:
    - compas_tna
  requires:
    - pip
  commands:
    - pip check

about:
  home: https://github.com/BlockResearchGroup/compas_tna
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: COMPAS package for Thrust Network Analaysis. This package provides the base implementation of TNA. For a RhinoVault-style user interface and workflow, see compas-RV2.
  doc_url: https://blockresearchgroup.github.io/compas_tna/
  dev_url: https://github.com/BlockResearchGroup/compas_tna

extra:
  recipe-maintainers:
    - tomvanmele
    - licini
